server:
  port: 8084
  servlet:
    context-path: "/ead-notification/"

spring:
  application:
    name: ead-notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/microservicenotification
    username: postgres
    password: banco123
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: Always
  rabbitmq:
    addresses: amqps://vtlbwywt:z9MKsvRuLkR1lE-nVzaQ9mwx7PPqqrGa@shrimp.rmq.cloudamqp.com/vtlbwywt

logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

ead:
  broker:
    exchange:
      notificationCommandExchange: ead.notificationcommand
    queue:
      notificationCommandQueue:
        name: ead.notificationcommand.ms.notification
    key:
      notificationCommandKey: ms.notification

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health
